title = "mysterium"
baseURL = "https://tera-mysterium.com"
publishDir = "docs"
languageCode = "en-us"
theme = "hugo-mysterium"
defaultContentLanguage = "en"
DefaultContentLanguageInSubdir = true
pluralizelisttitles = false

[params]
description = "TERA blog by seraphinush"
dateFormat = "Monday, January 2, 2006"
customJs = true
favicon = true
logo = true
analyticsId = "UA-66500356-2"
adsenseId = "ca-pub-3598595244893452"

[Languages]
[Languages.en]
  weight = 0
  contentDir = "content/en"
  [[Languages.en.params.nav]]
    title = "Discord"
    url = "https://discord.gg/A64RcA5"
  [[Languages.en.params.nav]]
    title = "Youtube"
    url = "https://www.youtube.com/c/seraphinush-gaming?sub_confirmation=1"
  [[Languages.en.params.nav]]
    title = "Twitch"
    url = "https://www.twitch.tv/seraphinush"
  [[Languages.en.params.nav]]
    title = "Patreon"
    url = "https://www.patreon.com/seraphinush"
  [[Languages.en.params.nav]]
    title = "Feedback"
    url = "https://github.com/seraphinush-gaming/mysterium/issues"

[Languages.ko]
  weight = 1
  contentDir = "content/ko"
  [[Languages.ko.params.nav]]
    title = "유튜브"
    url = "https://www.youtube.com/c/seraphinush-gaming?sub_confirmation=1"
  [[Languages.ko.params.nav]]
    title = "트위치"
    url = "https://www.twitch.tv/seraphinush"
  [[Languages.ko.params.nav]]
    title = "페이트리온"
    url = "https://www.patreon.com/seraphinush"
  [[Languages.ko.params.nav]]
    title = "피드백"
    url = "https://github.com/seraphinush-gaming/mysterium/issues"
